// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImportOreqM.Migrations
{
    [DbContext(typeof(OreqmContext))]
    [Migration("20240620065418_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Specdocument", b =>
                {
                    b.Property<int>("SpecdocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("covstatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("doctype")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("internalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("moduleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("oreqmViolations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("violations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("SpecdocumentId");

                    b.ToTable("Specdocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
